name: Release and Docker Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  bump-version:
    name: Bump Version and Update CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Bump version and update CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in token
        run: |
          echo "Running semantic-release..."
          semantic-release -vv --config releaserc.toml version --no-vcs-release
          echo "Version bump and CHANGELOG update complete."

  build-and-push-docker:
    name: Build and Push Multi-Platform Docker Images
    runs-on: ubuntu-latest
    needs: bump-version  # Run only if the bump-version job succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get latest Git tag
        id: get_tag
        run: |
          NEW_VERSION=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$NEW_VERSION" ]; then
            echo "Error: No Git tags found."
            exit 1
          fi
          echo "Latest Git tag: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "Building and pushing multi-platform Docker image with tag: $NEW_VERSION"

          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ghcr.io/$REPO_NAME:${{ env.NEW_VERSION }} \
            -t ghcr.io/$REPO_NAME:latest \
            -f docker/Dockerfile .
