name: Release and Docker Build

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  bump-version:
    name: Bump Version and Update CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for semantic-release to work

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semantic-release

      - name: Bump version and update CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for pushing changes
        run: |
          semantic-release -vv --config releaserc.toml version --no-vcs-release

      - name: Get bumped version
        id: get_version
        run: |
          # Extract the new version from the Git tag
          NEW_VERSION=$(git describe --tags --abbrev=0)
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: bump-version  # Run only if the bump-version job succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.NEW_VERSION }} -f docker/Dockerfile .

      - name: Push Docker image with version tag
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.NEW_VERSION }}

      - name: Tag Docker image as latest
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ env.NEW_VERSION }} ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image with latest tag
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
